const subjects=['人間の尊厳と自立','人間関係とコミュニケーション','社会の理解','生活支援技術','介護過程','こころとからだのしくみ','発達と老化の理解','認知症の理解','障害の理解','医療的ケア','総合問題'];

// PRNG deterministik (FNV-1a + mulberry32). Soal dibangun ulang tiap import — server, client,
// tiap build, dan juga dibaca scripts/gen-furigana.mjs — jadi TIDAK BOLEH pakai Math.random().
const hashSeed=(s)=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const rngFrom=(k)=>{let a=hashSeed(k);return ()=>{a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296}};
const shuffleSeeded=(arr,k)=>{const r=rngFrom(k),a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1)),t=a[i];a[i]=a[j];a[j]=t}return a};

// Bank template. Jawaban benar SELALU opsi yang berpusat pada利用者 (意思・尊厳・自立支援);
// pengecoh = paternalistik / demi kemudahan fasilitas. `answer` = index BENAR SEBELUM diacak.
// opts: [[JA, ID], ...] — dipasangkan supaya terjemahan ikut berpindah saat diacak.
const templates=[
 {q:'について、最も適切なものを1つ選びなさい。',qId:'pilih satu pernyataan yang paling tepat.',answer:0,opts:[['利用者の意思と生活歴を尊重して支援する','Mendukung dengan menghormati kehendak dan riwayat hidup pengguna'],['施設の効率を最優先して支援する','Mendukung dengan mendahulukan efisiensi fasilitas'],['本人に説明せず支援を開始する','Memulai bantuan tanpa menjelaskan kepada pengguna'],['家族の希望だけで決定する','Memutuskan hanya berdasarkan permintaan keluarga'],['観察せず推測だけで記録する','Mencatat berdasarkan dugaan tanpa observasi']],explanation:'Keputusan dalam kaigo harus berpusat pada pengguna: menjaga martabat, menjelaskan tindakan, dan bertumpu pada fakta observasi. Opsi lain mengabaikan kehendak atau keselamatan pengguna.'},
 {q:'に関する介護福祉職の対応として、最も適切なものを1つ選びなさい。',qId:'bagaimana respons petugas kaigo yang paling tepat?',answer:0,opts:[['本人ができる部分は見守り、必要な部分だけを介助する','Mengawasi bagian yang bisa dilakukan sendiri dan membantu hanya bagian yang perlu'],['時間がかかるので最初からすべてを介助する','Membantu semuanya sejak awal karena akan lama kalau ditunggu'],['失敗を防ぐために本人には何もさせない','Tidak membiarkan pengguna melakukan apa pun agar tidak gagal'],['危険に見える動作はすべてやめさせる','Menghentikan semua gerakan yang terlihat berisiko'],['介助の方法は職員の負担で決める','Menentukan metode bantuan berdasarkan beban staf']],explanation:'Inti jiritsu shien (自立支援) adalah menjaga kemampuan yang masih ada tetap terpakai: bantu seminimal mungkin, awasi sisanya. Mengambil alih semuanya (over-care) mempercepat hilangnya fungsi.'},
 {q:'について、記録と報告の方法として最も適切なものを1つ選びなさい。',qId:'bagaimana metode pencatatan dan pelaporan yang paling tepat?',answer:0,opts:[['観察した事実を具体的に記録し、必要な職種に報告する','Mencatat fakta yang teramati secara konkret dan melaporkannya ke profesi yang perlu tahu'],['自分の推測を事実として記録する','Mencatat dugaan pribadi sebagai fakta'],['記録は残さず口頭の申し送りだけで済ませる','Cukup serah-terima lisan tanpa meninggalkan catatan'],['都合の悪い変化は記録から省く','Menghilangkan perubahan yang tidak menguntungkan dari catatan'],['家族にだけ伝えて職員には伝えない','Hanya memberi tahu keluarga, tidak memberi tahu staf']],explanation:'Kiroku/houkoku (記録) memisahkan fakta objektif dari dugaan lalu membagikannya ke tim. Penghilangan data atau pelaporan lisan saja merusak kesinambungan dan keselamatan perawatan.'},
 {q:'の場面で利用者が支援を拒否した。介護福祉職の対応として、最も適切なものを1つ選びなさい。',qId:'saat pengguna menolak bantuan, apa respons yang paling tepat?',answer:0,opts:[['拒否の背景にある痛みや不安を確かめ、方法や時間を調整する','Memastikan nyeri atau kecemasan di balik penolakan, lalu menyesuaikan cara dan waktunya'],['決められた時間なので説得して続ける','Tetap melanjutkan sambil membujuk karena sudah masuk jadwal'],['問題行動として記録し、以後は声をかけない','Mencatatnya sebagai perilaku bermasalah lalu berhenti menyapa'],['本人が納得する前に手早く終わらせる','Menyelesaikannya cepat-cepat sebelum pengguna setuju'],['家族に連絡して本人を叱ってもらう','Menghubungi keluarga agar pengguna dimarahi']],explanation:'Penolakan adalah bentuk penyampaian kehendak, bukan sekadar "perilaku bermasalah". Yang perlu diperiksa: nyeri, kecemasan, kelelahan, lingkungan, dan jam pelaksanaan — lalu cara dan waktunya disesuaikan.'},
 {q:'について、支援を始める前の対応として最も適切なものを1つ選びなさい。',qId:'apa yang paling tepat dilakukan sebelum memulai bantuan?',answer:0,opts:[['本人に分かる言葉で目的と手順を説明し、同意を得てから始める','Menjelaskan tujuan dan langkah dengan bahasa yang dipahami pengguna, lalu memulai setelah ada persetujuan'],['認知症があるので説明は省略する','Melewatkan penjelasan karena pengguna punya demensia'],['説明は家族にだけ行い、本人には伝えない','Menjelaskan hanya kepada keluarga, tidak kepada pengguna'],['手が空いたときに黙って始める','Memulai tanpa berkata apa pun begitu ada waktu luang'],['書面を渡すだけで理解を確認しない','Cukup menyerahkan lembar tertulis tanpa memastikan pemahaman']],explanation:'Informed consent adalah wujud konkret penghormatan martabat dan penentuan diri. Adanya demensia bukan alasan melewatkan penjelasan — cara menjelaskannya yang disesuaikan, bukan dihapus.'},
 {q:'において、プライバシーと尊厳への配慮として最も適切なものを1つ選びなさい。',qId:'bagaimana bentuk kepedulian pada privasi dan martabat yang paling tepat?',answer:0,opts:[['排泄や入浴の介助では、カーテンやタオルで露出を最小限にする','Saat membantu eliminasi atau mandi, meminimalkan bagian terbuka dengan gorden atau handuk'],['忙しいときは居室の扉を開けたまま介助する','Membantu dengan pintu kamar tetap terbuka saat sedang sibuk'],['他の利用者の前で排泄の失敗について話す','Membicarakan kegagalan eliminasi di depan pengguna lain'],['知った個人情報を休憩室で話題にする','Menjadikan informasi pribadi yang diketahui sebagai obrolan di ruang istirahat'],['呼びかけは子ども扱いの愛称で統一する','Menyeragamkan sapaan dengan nama panggilan seperti kepada anak kecil']],explanation:'Perlindungan privasi dan sapaan yang santun sama pentingnya dengan keselamatan fisik dalam menjaga martabat (尊厳). Kesibukan bukan alasan untuk melewatkannya.'},
 {q:'について、多職種連携における介護福祉職の役割として最も適切なものを1つ選びなさい。',qId:'apa peran petugas kaigo dalam kolaborasi antarprofesi?',answer:0,opts:[['生活場面で気づいた変化を、具体的な事実として他職種に伝える','Menyampaikan perubahan yang disadari di situasi sehari-hari sebagai fakta konkret ke profesi lain'],['医療の判断なので気づいたことは伝えない','Tidak menyampaikan temuan karena itu wilayah penilaian medis'],['看護師の指示だけを待ち、自分では観察しない','Hanya menunggu instruksi perawat dan tidak mengamati sendiri'],['会議では意見を出さずに聞くだけにする','Di rapat hanya mendengarkan tanpa menyampaikan pendapat'],['他職種の記録は読まずに介助を進める','Melanjutkan bantuan tanpa membaca catatan profesi lain']],explanation:'Petugas kaigo adalah pihak yang paling lama mengamati kehidupan pengguna, sehingga informasinya menjadi titik awal team care. Penilaian klinis boleh milik profesi lain, tetapi observasi dan pelaporan tetap tugas kaigo.'},
 {q:'について、事故を防ぐための対応として最も適切なものを1つ選びなさい。',qId:'apa tindakan paling tepat untuk mencegah kecelakaan?',answer:0,opts:[['危険の要因を環境の側から見直し、本人の活動を制限しすぎない','Meninjau faktor bahaya dari sisi lingkungan tanpa membatasi aktivitas pengguna secara berlebihan'],['転倒の恐れがあるので歩行はやめてもらう','Meminta pengguna berhenti berjalan karena berisiko jatuh'],['事故が起きてから対策を考える','Baru memikirkan pencegahan setelah kecelakaan terjadi'],['ヒヤリハットは報告せず個人で気をつける','Tidak melaporkan near-miss dan cukup berhati-hati sendiri'],['安全のためにベッド周囲を柵で囲む','Mengelilingi tempat tidur dengan pembatas demi keamanan']],explanation:'Manajemen risiko menyeimbangkan keselamatan dan kemandirian, bukan menghentikan aktivitas. Berbagi laporan near-miss itulah yang mencegah kejadian terulang.'},
 {q:'に関する家族への対応として、最も適切なものを1つ選びなさい。',qId:'apa bentuk pendampingan keluarga yang paling tepat?',answer:0,opts:[['家族の負担や思いを聴き、本人の意思と家族の希望の両方を確認する','Mendengarkan beban dan perasaan keluarga, lalu memastikan kehendak pengguna maupun harapan keluarga'],['家族の希望を本人の意思より優先する','Mengutamakan harapan keluarga di atas kehendak pengguna'],['介護は専門職の仕事なので家族には関わらせない','Tidak melibatkan keluarga karena kaigo adalah pekerjaan tenaga profesional'],['家族の不安には触れず、事務的な連絡だけを行う','Tidak menyentuh kecemasan keluarga dan hanya memberi kabar administratif'],['本人の前で家族の対応を批判する','Mengkritik cara keluarga di depan pengguna']],explanation:'Keluarga sekaligus menjadi sasaran dukungan dan mitra kerja. Perasaan keluarga diterima, tetapi titik pusat pengambilan keputusan tetap kehendak pengguna.'},
 {q:'について、介護過程の進め方として最も適切なものを1つ選びなさい。',qId:'bagaimana alur proses kaigo yang paling tepat?',answer:0,opts:[['情報を収集して課題を明確にし、本人と目標を共有して計画する','Mengumpulkan informasi, memperjelas masalah, lalu menyusun rencana dengan tujuan yang disepakati bersama pengguna'],['経験に基づいて計画を立て、本人には伝えない','Menyusun rencana berdasarkan pengalaman dan tidak memberitahukannya ke pengguna'],['一度立てた計画は評価せずに続ける','Menjalankan rencana terus tanpa pernah dievaluasi'],['課題は職員の負担が少ない順に決める','Menentukan prioritas masalah dari yang paling ringan bagi staf'],['アセスメントを省いて計画から始める','Melewati asesmen dan langsung menyusun rencana']],explanation:'Kaigo katei (介護過程) adalah siklus asesmen → perumusan masalah → tujuan & rencana → pelaksanaan → evaluasi. Tujuan yang tidak disepakati bersama pengguna membuat seluruh siklus kehilangan dasarnya.'},
 {q:'について、利用者の権利を守る対応として最も適切なものを1つ選びなさい。',qId:'apa tindakan paling tepat untuk melindungi hak pengguna?',answer:0,opts:[['身体拘束は原則行わず、代わりの方法をチームで検討する','Pada prinsipnya tidak melakukan pengekangan fisik dan mencari metode alternatif bersama tim'],['危険なので本人の同意なく車いすにベルトを付ける','Memasang sabuk di kursi roda tanpa persetujuan pengguna karena berbahaya'],['虐待が疑われても確証がなければ報告しない','Tidak melaporkan dugaan penganiayaan selama belum ada bukti pasti'],['判断力が低下した人の希望は聞かなくてよい','Menganggap harapan orang dengan penurunan daya nilai tidak perlu didengar'],['苦情は事業所の中だけで処理し記録に残さない','Menangani keluhan hanya di dalam lembaga tanpa mencatatnya']],explanation:'Shintai kousoku (身体拘束) pada prinsipnya dilarang; pengecualian darurat menuntut tiga syarat dan pencatatan. Dugaan penganiayaan pun sudah wajib dilaporkan, tidak perlu menunggu bukti pasti.'},
 {q:'に関する次の記述のうち、正しいものを1つ選びなさい。',qId:'manakah pernyataan yang benar?',answer:0,opts:[['制度や技術は、利用者の生活と意思に結びつけて理解する必要がある','Sistem dan teknik perlu dipahami dengan menghubungkannya ke kehidupan dan kehendak pengguna'],['用語を暗記すれば事例に当てはめる必要はない','Kalau istilah sudah dihafal, tidak perlu diterapkan ke kasus'],['手順を覚えれば目的は考えなくてよい','Kalau urutan langkah sudah dihafal, tujuannya tidak perlu dipikirkan'],['試験に出る部分だけを理解すればよい','Cukup memahami bagian yang keluar di ujian saja'],['判断は自分の経験だけを基準にすればよい','Penilaian cukup berdasarkan pengalaman pribadi saja']],explanation:'Pengetahuan baru berguna ketika dikaitkan dengan kasus nyata. Hafalan istilah dan urutan langkah tanpa memahami tujuannya tidak terpakai, baik di ujian nasional maupun di lapangan.'}
];

// stride 7 coprime dengan 12 → template soal berurutan selalu berbeda; subject berputar tiap 11,
// jadi kombinasi subject×template baru berulang setelah 132 soal (> 125 soal per tahun).
function q(no,year){const topic=subjects[(no-1)%subjects.length],tpl=templates[(no*7+hashSeed(String(year)))%templates.length],opts=shuffleSeeded(tpl.opts,`${year}-${no}`),answer=String(opts.indexOf(tpl.opts[tpl.answer])+1);return {no,subjectGroup:((no-1)%11)+1,subject:topic,prompt:{ja:`${topic}${tpl.q}`,id:`Tentang ${topic}, ${tpl.qId}`},options:opts.map((o,i)=>({key:String(i+1),text:{ja:o[0],id:o[1]}})),answer,explanation:{id:tpl.explanation},terms:[]}}
function make(year){return {year,exam:`第${year-1988}回`,examDate:`${year}-01-31`,totalQuestions:125,available:true,parts:[1,2,3,4,5].map(part=>({part,from:(part-1)*25+1,to:part*25})),questions:Array.from({length:125},(_,i)=>q(i+1,year))}}
export default Object.fromEntries([2021,2022,2023,2024,2025,2026].map(y=>[y,make(y)]));
