import React,{useState,useEffect} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {ChevronRight} from 'lucide-react';
import finalData from './content/final/index.js';
import Furigana from './Furigana.jsx';
import {useLangMode} from './lib/social.jsx';

const parts=[1,2,3,4,5],years=[2026,2025,2024,2023,2022,2021],key='kk_final_progress';
const readProgress=()=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}};
const saveProgress=x=>{try{localStorage.setItem(key,JSON.stringify(x))}catch{}};
/* UUID attemptId: pola sama Quiz di main.jsx — crypto.randomUUID + fallback
   getRandomValues supaya versi lama tetap menghasilkan UUID valid (server 400 kalau bukan). */
const uuid=()=>crypto.randomUUID?crypto.randomUUID():([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,c=>(c^crypto.getRandomValues(new Uint8Array(1))[0]&15>>c/4).toString(16));
/* Progress ujian sekarang SERVER-FIRST (api/final.mjs). localStorage jadi dua hal:
   (1) fallback offline — entri ditandai saved:false dan direplay FinalResult /
   submit berikutnya lewat /api/final/local-merge (upsert idempoten, tanpa XP retroaktif);
   (2) sumber merge data lama era-guest, dikirim sekali (flag kk_final_merged).
   `cache` meniru bentuk lama {year:{part:{best,answered,answers,mode,saved}}}
   supaya komponen layar tidak perlu tahu dari mana datanya datang. */
let cache={};
async function ensureProgress(){try{const r=await fetch('/api/final',{credentials:'same-origin'});if(!r.ok)return;const d=await r.json();cache={};for(const [y,ps] of Object.entries(d.progress||{}))cache[Number(y)]=Object.fromEntries(Object.entries(ps).map(([n,e])=>[Number(n),{...e,saved:true}]));const loc=readProgress();for(const [y,ps] of Object.entries(loc)){cache[Number(y)]=cache[Number(y)]||{};for(const [n,e] of Object.entries(ps)){const s=cache[Number(y)][Number(n)];if(!s||!s.saved)cache[Number(y)][Number(n)]={...e,saved:false};}}mergeLocalToServer();}catch{cache=readProgress();for(const y of Object.keys(cache))for(const n of Object.keys(cache[y]))cache[y][n]={...cache[y][n],saved:false}}}
const getProgress=()=>cache;
async function loadPart(y,n){if(!Object.keys(cache).length)await ensureProgress();const s=cache[y]?.[n];if(s)return s;const loc=readProgress()[y]?.[n];return loc?{...loc,saved:false}:{}}
/* Kirim semua entri lokal yang belum diakui server. Fire-and-forget; upsert server
   tidak menaikkan attempts saat konflik, jadi aman dipanggil berulang-ulang. */
function mergeLocalToServer(){const loc=readProgress(),entries=[];for(const [y,ps] of Object.entries(loc))for(const [n,e] of Object.entries(ps))entries.push({year:Number(y),part:Number(n),best:Number(e.best)||0,answered:Number(e.answered)||0,answers:e.answers||{},mode:e.mode});if(!entries.length)return;fetch('/api/final/local-merge',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({entries})}).catch(()=>{});}
function savePart(y,n,e){const all=readProgress();all[y]={...(all[y]||{}),[n]:{best:Math.max(all[y]?.[n]?.best||0,e.best||0),answered:e.answered||0,answers:e.answers||{},mode:e.mode}};saveProgress(all);cache[y]={...(cache[y]||{}),[n]:{...all[y][n],saved:false}};mergeLocalToServer();}
/* Semua teks Jepang lewat <Furigana>. Catatan: `mode` di FinalQuiz itu practice/exam,
   bukan bahasa — makanya bahasa dipegang state `lang` yang terpisah. */
function LangPicker({lang,setLang}){return <div className="finalModeSwitch">{['kanji','furigana','id'].map(m=><button key={m} className={lang===m?'active':''} onClick={()=>setLang(m)}>{m==='kanji'?'漢字':m==='furigana'?'ふり':'ID'}</button>)}</div>}
function YearCard({year,p}){const d=finalData[year];return <Link className="finalYearCard" to={`/final/${year}`}><b>{year}</b><strong>{d.exam}</strong><span>{parts.filter(n=>p[n]).length}/5 bagian</span><small>125 soal</small></Link>}
export function UnlimitedFinal(){const [q,setQ]=useState(1),[selected,setSelected]=useState(null),[lang,setLang]=useLangMode();const item=finalData[2026].questions[q-1];return <main className="page finalPage unlimitedFinal"><Link to="/final" className="back">← Ujian Akhir</Link><div className="unlimitedHero"><p className="eyebrow">UNLIMITED PRACTICE</p><h1>Latihan tanpa batas</h1><p className="muted">Soal terus berputar. Tidak memengaruhi skor resmi, XP, atau progress ujian.</p></div><LangPicker lang={lang} setLang={setLang}/><section className="finalQuestion"><small>Soal latihan #{q}</small><Furigana field={item.prompt} mode={lang} as="h2"/><div className="finalOptions">{item.options.map(o=><button className={selected===o.key?'selected':''} key={o.key} onClick={()=>setSelected(o.key)}><b>{o.key}</b><Furigana field={o.text} mode={lang} variant="opt"/></button>)}</div>{selected&&<div className="finalFeedback">{selected===item.answer?'Benar ✨':'Coba lagi ya'}<br/>{item.explanation.id}</div>}</section><button className="primary big" onClick={()=>{setQ(q%125+1);setSelected(null)}}>Soal berikutnya <ChevronRight/></button></main>}
export function FinalHome(){const [prog,setProg]=useState({});useEffect(()=>{ensureProgress().then(()=>{setProg(getProgress());if(!localStorage.getItem('kk_final_merged')){mergeLocalToServer();try{localStorage.setItem('kk_final_merged','1')}catch{}}});},[]);return <main className="page finalPage"><Link to="/belajar" className="back">← Belajar</Link><div className="finalHero"><p className="eyebrow">SIMULASI UJIAN</p><h1>Ujian Akhir</h1><p className="muted">Pilih tahun ujian. Semua bagian terbuka sejak awal.</p></div><Link className="unlimitedBanner" to="/final/unlimited"><b>🌸 Latihan tanpa batas</b><span>Jawab soal random seperti mode Latihan sebelumnya →</span></Link><div className="finalYearGrid">{years.map(y=><YearCard key={y} year={y} p={prog[y]||{}}/>)}</div></main>}
export function FinalYear(){const {year}=useParams(),y=Number(year),d=finalData[y];const [p,setP]=useState({});useEffect(()=>{ensureProgress().then(()=>setP(getProgress()[y]||{}));},[y]);if(!d)return <main className="page"><h1>Tahun tidak ditemukan</h1><Link to="/final">Kembali</Link></main>;return <main className="page finalPage"><Link to="/final" className="back">← Semua tahun</Link><h1>{y} · {d.exam}</h1><p className="muted">{Object.values(p).reduce((a,x)=>a+(x.best||0),0)}/125 terbaik</p><div className="finalParts">{parts.map(part=>{const from=(part-1)*25+1,to=part*25,x=p[part];return <Link key={part} to={`/final/${y}/part/${part}`} className="finalPart"><b>Bagian {part}</b><span>soal {from}–{to}</span><small>{x?`${x.best}/25`:'Belum dikerjakan'}</small></Link>})}</div></main>}
// `ok` wajib: slice() nerima indeks negatif & non-integer, jadi tanpa cek ini /final/2021/part/-1
// nyajikan soal 76-100 dengan label "Bagian -1", dan part/1.5 nyajikan soal 13-37 (nyeberang dua
// bagian). Number.isInteger sekaligus nolak NaN, jadi param non-numerik ikut ketangkep.
export function FinalQuiz(){const {year,part}=useParams(),y=Number(year),n=Number(part),d=finalData[y],ok=Number.isInteger(n)&&n>=1&&n<=parts.length,qs=ok?(d?.questions?.slice((n-1)*25,n*25)||[]):[],nav=useNavigate();const [mode,setMode]=useState(()=>localStorage.getItem('kk_final_mode')||'practice'),[lang,setLang]=useLangMode(),[answers,setAnswers]=useState({}),[qi,setQi]=useState(0),[attemptId,setAttemptId]=useState(uuid),[submitErr,setSubmitErr]=useState(null);const q=qs[qi];if(!d||!qs.length)return <main className="page"><h1>Soal belum tersedia</h1></main>;const choose=k=>setAnswers(a=>({...a,[q.no]:k}));const patchPrefMode=m=>fetch('/api/final',{method:'PATCH',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:m})}).catch(()=>{});
/* Submit server-first: jawaban dikirim mentah, skor dihitung ulang di server dari
   bank soal deterministik. Gagal jaringan → simpan lokal (saved:false) lalu tetap
   lanjut ke Result; entri itu direplay otomatis saat Result terbuka lagi online.
   Gagal 400 (selain UUID usang) → banner error TANPA pindah halaman, retry idempoten
   dengan attemptId yang sama. */
const submit=async()=>{setSubmitErr(null);const answered=Object.keys(answers).length;try{const r=await fetch('/api/final',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({year:y,part:n,mode,answers,attemptId})});if(r.status===400){const b=await r.json().catch(()=>({}));if(b.message==='attemptId must be a UUID'){setAttemptId(uuid());return}setSubmitErr(b.message||'Submit ditolak server.');return}if(!r.ok){setSubmitErr('Gagal menyimpan progress. Coba lagi.');return}const b=await r.json();const all=readProgress();all[y]={...(all[y]||{}),[n]:{best:b.best,answered,answers,mode}};saveProgress(all);cache[y]={...(cache[y]||{}),[n]:{best:b.best,answered,answers,mode,saved:true}};nav(`/final/${year}/part/${part}/result`)}catch{savePart(y,n,{best:qs.reduce((a,x)=>a+(answers[x.no]===x.answer?1:0),0),answered,answers,mode});nav(`/final/${year}/part/${part}/result`)}};
return <main className="page finalQuiz"><div className="finalQuizTop"><Link to={`/final/${year}`}>× Tutup</Link><span>問題 {q.no} · {qi+1}/25</span><select value={mode} onChange={e=>{setMode(e.target.value);localStorage.setItem('kk_final_mode',e.target.value);patchPrefMode(e.target.value)}}><option value="practice">Mode Latihan</option><option value="exam">Mode Ujian</option></select></div><LangPicker lang={lang} setLang={setLang}/><div className="finalQuestion"><Furigana field={q.prompt} mode={lang} as="h2"/><div className="finalOptions">{q.options.map(o=><button className={answers[q.no]===o.key?'selected':''} key={o.key} onClick={()=>choose(o.key)}><b>{o.key}</b><Furigana field={o.text} mode={lang} variant="opt"/></button>)}</div>{mode==='practice'&&answers[q.no]&&<div className="finalFeedback">{answers[q.no]===q.answer?'Benar':'Cek lagi'} — {q.explanation.id}</div>}</div>{submitErr&&<div className="submitError">{submitErr}</div>}<div className="finalQuizNav"><button disabled={qi===0} onClick={()=>setQi(qi-1)}>Sebelumnya</button>{qi<24?<button onClick={()=>setQi(qi+1)}>Berikutnya</button>:<button onClick={submit}>Kirim bagian</button>}</div></main>}
export function FinalResult(){const {year,part}=useParams(),y=Number(year),n=Number(part);const [p,setP]=useState(null);useEffect(()=>{if(!finalData[y]||!Number.isInteger(n)||n<1||n>parts.length)return;loadPart(y,n).then(e=>{if(e&&!e.saved&&e.answers){savePart(y,n,{best:e.best||0,answered:e.answered||0,answers:e.answers,mode:e.mode});e={...e,saved:true}}setP(e||{});});},[y,n]);if(!finalData[y]||!Number.isInteger(n)||n<1||n>parts.length)return <main className="page"><h1>Hasil tidak ditemukan</h1><Link to="/final">Kembali</Link></main>;return <main className="page finalPage"><p className="eyebrow">HASIL BAGIAN {n}</p>{p===null?<p className="muted">Memuat hasil…</p>:<><h1>{p?.best||0} / 25</h1><p className="muted">Jawaban tersimpan di akunmu.</p></>}<Link className="primary big" to={`/final/${y}`}>Kembali ke tahun {y}</Link></main>}
