import React,{useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {ChevronRight} from 'lucide-react';
import finalData from './content/final/index.js';

const parts=[1,2,3,4,5],years=[2026,2025,2024,2023,2022,2021],key='kk_final_progress';
const readProgress=()=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}};
const saveProgress=x=>{try{localStorage.setItem(key,JSON.stringify(x))}catch{}};
function text(field,mode){if(mode==='id')return field.id;if(mode==='furigana')return field.ja;return field.ja}
function YearCard({year}){const d=finalData[year],p=readProgress()[year]||{};return <Link className="finalYearCard" to={`/final/${year}`}><b>{year}</b><strong>{d.exam}</strong><span>{Object.keys(p).length}/5 bagian</span><small>125 soal</small></Link>}
export function UnlimitedFinal(){const [q,setQ]=useState(1),[selected,setSelected]=useState(null),[mode,setMode]=useState('kanji');const item=finalData[2026].questions[q-1];return <main className="page finalPage unlimitedFinal"><Link to="/final" className="back">← Ujian Akhir</Link><div className="unlimitedHero"><p className="eyebrow">UNLIMITED PRACTICE</p><h1>Latihan tanpa batas</h1><p className="muted">Soal terus berputar. Tidak memengaruhi skor resmi, XP, atau progress ujian.</p></div><div className="finalModeSwitch">{['kanji','furigana','id'].map(m=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{m==='kanji'?'漢字':m==='furigana'?'ふり':'ID'}</button>)}</div><section className="finalQuestion"><small>Soal latihan #{q}</small><h2>{text(item.prompt,mode)}</h2><div className="finalOptions">{item.options.map(o=><button className={selected===o.key?'selected':''} key={o.key} onClick={()=>setSelected(o.key)}><b>{o.key}</b><span>{text(o.text,mode)}</span></button>)}</div>{selected&&<div className="finalFeedback">{selected===item.answer?'Benar ✨':'Coba lagi ya'}<br/>{item.explanation.id}</div>}</section><button className="primary big" onClick={()=>{setQ(q%125+1);setSelected(null)}}>Soal berikutnya <ChevronRight/></button></main>}
export function FinalHome(){return <main className="page finalPage"><Link to="/" className="back">← Belajar</Link><div className="finalHero"><p className="eyebrow">SIMULASI UJIAN</p><h1>Ujian Akhir</h1><p className="muted">Pilih tahun ujian. Semua bagian terbuka sejak awal.</p></div><Link className="unlimitedBanner" to="/final/unlimited"><b>🌸 Latihan tanpa batas</b><span>Jawab soal random seperti mode Latihan sebelumnya →</span></Link><div className="finalYearGrid">{years.map(y=><YearCard key={y} year={y}/>)}</div></main>}
export function FinalYear(){const {year}=useParams(),y=Number(year),d=finalData[y];if(!d)return <main className="page"><h1>Tahun tidak ditemukan</h1><Link to="/final">Kembali</Link></main>;const p=readProgress()[y]||{};return <main className="page finalPage"><Link to="/final" className="back">← Semua tahun</Link><h1>{y} · {d.exam}</h1><p className="muted">{Object.values(p).reduce((a,x)=>a+(x.best||0),0)}/125 terbaik</p><div className="finalParts">{parts.map(part=>{const from=(part-1)*25+1,to=part*25,x=p[part];return <Link key={part} to={`/final/${y}/part/${part}`} className="finalPart"><b>Bagian {part}</b><span>soal {from}–{to}</span><small>{x?`${x.best}/25`:'Belum dikerjakan'}</small></Link>})}</div></main>}
export function FinalQuiz(){const {year,part}=useParams(),y=Number(year),n=Number(part),d=finalData[y],qs=d?.questions?.slice((n-1)*25,n*25)||[],nav=useNavigate();const [mode,setMode]=useState(()=>localStorage.getItem('kk_final_mode')||'practice'),[answers,setAnswers]=useState({}),[qi,setQi]=useState(0);const q=qs[qi];if(!d||!qs.length)return <main className="page"><h1>Soal belum tersedia</h1></main>;const choose=k=>setAnswers(a=>({...a,[q.no]:k}));const submit=()=>{const correct=qs.reduce((a,x)=>a+(answers[x.no]===x.answer?1:0),0),all=readProgress();all[y]={...(all[y]||{}),[n]:{best:Math.max(all[y]?.[n]?.best||0,correct),answered:Object.keys(answers).length,answers}};saveProgress(all);nav(`/final/${year}/part/${part}/result`)};return <main className="page finalQuiz"><div className="finalQuizTop"><Link to={`/final/${year}`}>× Tutup</Link><span>問題 {q.no} · {qi+1}/25</span><select value={mode} onChange={e=>{setMode(e.target.value);localStorage.setItem('kk_final_mode',e.target.value)}}><option value="practice">Mode Latihan</option><option value="exam">Mode Ujian</option></select></div><div className="finalQuestion"><h2>{text(q.prompt,mode)}</h2><div className="finalOptions">{q.options.map(o=><button className={answers[q.no]===o.key?'selected':''} key={o.key} onClick={()=>choose(o.key)}><b>{o.key}</b><span>{text(o.text,mode)}</span></button>)}</div>{mode==='practice'&&answers[q.no]&&<div className="finalFeedback">{answers[q.no]===q.answer?'Benar':'Cek lagi'} — {q.explanation.id}</div>}</div><div className="finalQuizNav"><button disabled={qi===0} onClick={()=>setQi(qi-1)}>Sebelumnya</button>{qi<24?<button onClick={()=>setQi(qi+1)}>Berikutnya</button>:<button onClick={submit}>Kirim bagian</button>}</div></main>}
export function FinalResult(){const {year,part}=useParams(),p=readProgress()[Number(year)]?.[Number(part)];return <main className="page finalPage"><p className="eyebrow">HASIL BAGIAN {part}</p><h1>{p?.best||0} / 25</h1><p className="muted">Jawaban tersimpan di perangkat ini.</p><Link className="primary big" to={`/final/${year}`}>Kembali ke tahun {year}</Link></main>}
