import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,Link,useNavigate,useParams,useLocation,Navigate,useLocation as useRouterLocation} from 'react-router-dom';
import {Heart,Lock,ChevronRight,BookOpen,Flame,UserRound,Star,Check,Volume2,Info,Menu,Home as HomeIcon,Languages,ArrowLeft,SkipForward,RotateCcw} from 'lucide-react';
import {sections,getSection,getLevel,glossary} from './data.js';
import Login from './Login.jsx';
import './styles.css';import './translation.css';import './routing.css';import './auth.css';

const progressKey='kaigoKittyProgress';
function readProgress(){try{return JSON.parse(localStorage.getItem(progressKey)||'{"done":{},"xp":120,"streak":3}') }catch{return {done:{},xp:120,streak:3}}}
function saveProgress(p){localStorage.setItem(progressKey,JSON.stringify(p))}
function Mascot({mood='idle'}){return <div className={`mascot mascot-${mood}`} aria-label="Kenshi-chan original mascot"><span className="catEar left"/><span className="catEar right"/><span className="catFace">{mood==='happy'?'ฅ^•ﻌ•^ฅ':mood==='sad'?'｡°(°´ᯅ`°)°｡':'ฅ^•ﻌ•^ฅ'}</span><span className="bow">🎀</span></div>}
function Shell({children}){const [p,setP]=useState(readProgress);const loc=useLocation();useEffect(()=>{const f=()=>setP(readProgress());addEventListener('storage',f);return()=>removeEventListener('storage',f)},[]);return <div className="app"><header><Link to="/" className="brand"><div className="kitty">🎀</div><div><b>kaigo kitty</b><small>learn with care</small></div></Link><div className="topStats"><span><Flame size={18} fill="#ff718f"/> {p.streak}</span><span><Heart size={18} fill="#ff718f"/> {p.xp} XP</span><Link to="/login"><UserRound size={20}/></Link></div></header>{children}<nav><Link className={loc.pathname==='/'?'active':''} to="/"><HomeIcon/><span>Home</span></Link><Link className={loc.pathname.startsWith('/glossary')?'active':''} to="/glossary"><Languages/><span>Glossary</span></Link><Link className={loc.pathname==='/profile'?'active':''} to="/profile"><UserRound/><span>Profile</span></Link></nav></div>}
function Home(){const p=readProgress();return <main><section className="welcome"><div><p className="eyebrow">OHAYŌ, KENSHI 🌷</p><h1>Belajar merawat<br/><em>dengan hati.</em></h1><p className="muted">13 section · {sections.reduce((a,s)=>a+s.levelCount,0)} level · pelan-pelan sampai mahir.</p></div><Mascot/></section><div className="daily"><div><b>Daily care</b><p>Setiap kartu kecil membuatmu lebih dekat.</p><div className="progress"><i style={{width:`${Math.min(100,(Object.keys(p.done).length/sections.reduce((a,s)=>a+s.levelCount,0))*100)}%`}}/></div></div><span className="badge">{Object.keys(p.done).length} done</span></div><div className="sectionHead"><div><h2>Learning path</h2><p>Dari fondasi sampai case study ✨</p></div><button className="round"><Menu size={19}/></button></div><div className="sectionGrid">{sections.map((s,i)=><SectionCard key={s.id} section={s} locked={i>0&&Object.keys(p.done).filter(k=>k.startsWith(`${i}-`)).length===0}/>)}</div></main>}
function SectionCard({section,locked}){const p=readProgress();const done=section.levels.filter(l=>p.done[`${section.id}-${l.id}`]).length;return <Link to={locked?'#':`/section/${section.id}`} onClick={e=>locked&&e.preventDefault()} className={`sectionCard ${locked?'locked':''}`}><div className="sectionIcon">{locked?<Lock size={22}/>:section.icon}</div><div className="sectionCopy"><small>SECTION {String(section.id).padStart(2,'0')}</small><b>{section.titleJa}</b><span>{section.titleId}</span><div className="miniProgress"><i style={{width:`${done/section.levelCount*100}%`}}/></div><em>{done}/{section.levelCount} levels</em></div><ChevronRight/></Link>}
function SectionOverview(){const {sectionId}=useParams();const s=getSection(sectionId);const p=readProgress();if(!s)return <Navigate to="/"/>;return <main className="page"><Link to="/" className="back"><ArrowLeft size={16}/> Learning path</Link><div className="sectionHero"><span>{s.icon}</span><div><small>SECTION {s.id}</small><h1>{s.titleJa}</h1><p>{s.titleId}</p></div></div><p className="muted">{s.description}</p><div className="recapLink"><Link to={`/section/${s.id}/recap`}><Star fill="#ffb73b"/> Section recap <span>{s.levelCount} level review</span><ChevronRight/></Link></div><div className="levelList">{s.levels.map((l,i)=>{const locked=i>0&&!p.done[`${s.id}-${i}`];return <Link key={l.id} className={`levelRow ${locked?'locked':''}`} to={locked?'#':`/section/${s.id}/level/${l.id}`} onClick={e=>locked&&e.preventDefault()}><div className="levelNum">{locked?<Lock size={16}/>:p.done[`${s.id}-${l.id}`]?<Check/>:l.id}</div><div><small>LEVEL {l.id}</small><b>{l.titleJa}</b><span>{l.titleId}</span></div><ChevronRight/></Link>})}</div></main>}
function LevelHub(){const {sectionId,levelId}=useParams();const s=getSection(sectionId),l=getLevel(sectionId,levelId);if(!s||!l)return <Navigate to="/"/>;return <main className="page"><Link to={`/section/${s.id}`} className="back"><ArrowLeft size={16}/> {s.titleJa}</Link><div className="levelHero"><Mascot/><div><small>LEVEL {l.id}</small><h1>{l.titleJa}</h1><p>{l.titleId}</p></div></div><div className="objective"><Info/><div><b>今日の目標</b><p>{l.objectiveId}</p></div></div><div className="flowButtons"><Link className="primary big" to={`/section/${s.id}/level/${l.id}/materi`}><BookOpen/> Baca materi dulu <ChevronRight/></Link><Link className="secondary big" to={`/section/${s.id}/level/${l.id}/quiz`}><Star/> Langsung quiz <ChevronRight/></Link></div><div className="preview"><b>{l.materi.length} kartu materi · {l.questions.length} soal</b><p>Materi bisa di-next atau langsung di-skip kapan saja.</p></div></main>}
function Materi(){const {sectionId,levelId}=useParams();const s=getSection(sectionId),l=getLevel(sectionId,levelId);const [i,setI]=useState(0);const nav=useNavigate();const card=l?.materi[i];if(!s||!l)return <Navigate to="/"/>;return <main className="page materiPage"><div className="quizTop"><Link to={`/section/${s.id}/level/${l.id}`} className="back">× Tutup</Link><span>MATERI {i+1}/{l.materi.length}</span></div><div className="quizProgress"><i style={{width:`${(i+1)/l.materi.length*100}%`}}/></div><div className="materiCard"><Mascot mood="happy"/><small>MINI LESSON</small><h1>{card.titleJa}</h1><h2>{card.titleId}</h2><p className="japanese">{card.bodyJa}</p><div className="translation">{card.bodyId}</div>{card.terms.length>0&&<div className="terms">{card.terms.map(t=><Link key={t} to={`/glossary?term=${encodeURIComponent(t)}`}>#{t}</Link>)}</div>}</div><div className="materiActions"><button className="secondary" onClick={()=>nav(`/section/${s.id}/level/${l.id}/quiz`)}><SkipForward/> Skip to quiz</button><button className="primary" onClick={()=>i<l.materi.length-1?setI(i+1):nav(`/section/${s.id}/level/${l.id}/quiz`)}>{i<l.materi.length-1?'Next card':'Mulai quiz'} <ChevronRight/></button></div></main>}
function Quiz(){const {sectionId,levelId}=useParams();const s=getSection(sectionId),l=getLevel(sectionId,levelId);const [qi,setQi]=useState(0),[selected,setSelected]=useState(null),[showId,setShowId]=useState(false),[score,setScore]=useState(0),[saving,setSaving]=useState(false);const nav=useNavigate();if(!s||!l)return <Navigate to="/"/>;const q=l.questions[qi%l.questions.length];const answer=i=>{if(selected!==null)return;setSelected(i);if(i===q.correctIndex)setScore(x=>x+1)};const next=async()=>{if(qi<4){setQi(x=>x+1);setSelected(null);setShowId(false)}else{const finalScore=score+(selected===q.correctIndex?1:0);setSaving(true);const xpEarned=finalScore*10+30;try{const r=await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sectionId:s.id,levelId:l.id,score:finalScore,xpEarned})});if(r.status===401){const p=readProgress();p.done[`${s.id}-${l.id}`]=true;p.xp+=xpEarned;saveProgress(p)}else if(!r.ok)throw new Error('progress save failed')}catch{const p=readProgress();p.done[`${s.id}-${l.id}`]=true;p.xp+=xpEarned;saveProgress(p)}finally{setSaving(false);nav(`/section/${s.id}/level/${l.id}/result`,{state:{score:finalScore,total:5}})}}};return <main className="page quizPage"><div className="quizTop"><Link to={`/section/${s.id}/level/${l.id}`} className="back">‹ Exit</Link><span>{qi+1} / 5</span></div><div className="quizProgress"><i style={{width:`${(qi+1)*20}%`}}/></div><div className="questionCard"><p className="source">{q.sourceYear} · {q.difficulty}</p><h1>{q.questionJa}</h1><button className="translateToggle" onClick={()=>setShowId(!showId)}>{showId?'Tutup terjemahan':'Klik untuk terjemahan'} <span>{showId?'−':'+'}</span></button>{showId&&<div className="translation">{q.questionId}</div>}<button className="listen"><Volume2 size={17}/> 用語を聞く · Dengarkan istilah</button></div><div className="choices">{q.choices.map((c,i)=><button key={i} onClick={()=>answer(i)} className={selected!==null?(i===q.correctIndex?'correct':i===selected?'wrong':''):''}><span>{String.fromCharCode(65+i)}</span><b>{c}</b>{selected!==null&&i===q.correctIndex&&<Check/>}</button>)}</div>{selected!==null&&<div className={`explain ${selected===q.correctIndex?'good':''}`}><Info/><div><b>{selected===q.correctIndex?'Sugoi! 正解です。':'もう一度、考えてみよう。'}</b><p>{q.explanationJa}</p><small>{q.explanationId}</small><Link to={`/glossary?term=${encodeURIComponent('自立支援')}`}>Buka kartu istilah →</Link></div></div>}{selected!==null&&<button className="continue primary" onClick={next}>{qi<4?'Lanjut':'Lihat hasil'} <ChevronRight/></button>}</main>}
function Result(){const {sectionId,levelId}=useParams();const {state}=useLocation();const s=getSection(sectionId),l=getLevel(sectionId,levelId);return <main className="page result"><Mascot mood={state?.score===state?.total?'happy':'idle'}/><p className="eyebrow">LEVEL COMPLETE ✨</p><h1>{state?.score||0} / {state?.total||5}</h1><p className="muted">{state?.score===state?.total?'完璧！Perfect!':'Bagus, terus latihan sedikit lagi.'}</p><div className="resultStats"><b>+{(state?.score||0)*10+30} XP</b><span>Materi: {l?.titleId}</span></div><div className="flowButtons"><Link className="primary big" to={Number(levelId)<s.levelCount?`/section/${s.id}/level/${Number(levelId)+1}`:`/section/${s.id}/recap`}>Level berikutnya <ChevronRight/></Link><Link className="secondary big" to={`/section/${s.id}/level/${levelId}/quiz`}><RotateCcw/> Ulangi</Link></div></main>}
function Recap(){const {sectionId}=useParams(),s=getSection(sectionId);if(!s)return <Navigate to="/"/>;return <main className="page result"><div className="sectionHero"><span>{s.icon}</span><div><small>RECAP</small><h1>{s.titleJa}</h1><p>Section review · {s.titleId}</p></div></div><Mascot mood="happy"/><h2>Ready for a little challenge?</h2><p className="muted">Uji pemahamanmu dengan soal campuran dari semua level.</p><Link className="primary big" to={`/section/${s.id}/level/1/quiz`}>Mulai recap <Star/></Link></main>}
function Glossary(){const [term,setTerm]=useState(new URLSearchParams(useLocation().search).get('term')||'');const list=useMemo(()=>glossary.filter(x=>(x.ja+x.reading+x.id).toLowerCase().includes(term.toLowerCase())),[term]);return <main className="page"><h1 className="pageTitle">Glossary <span>用語カード</span></h1><input className="search" value={term} onChange={e=>setTerm(e.target.value)} placeholder="Cari 尊厳 / dignity..."/>{list.map(x=><a className="glossaryRow" key={x.ja} href="https://ryuken25.github.io/kenshi-kanji-n4/" target="_blank" rel="noreferrer"><div><b>{x.ja}</b><small>{x.reading}</small></div><span>{x.id}</span><ChevronRight/></a>)}</main>}
function Profile(){const p=readProgress();return <main className="page profile"><div className="profileCard"><Mascot mood="happy"/><h1>Kenshi's care journey</h1><p className="muted">Belajar dengan lembut, tumbuh dengan konsisten.</p><div className="stats"><div><b>{p.xp}</b><small>total XP</small></div><div><b>{p.streak}</b><small>day streak</small></div><div><b>{Object.keys(p.done).length}</b><small>levels</small></div></div></div><div className="tip"><Star fill="#ffb73b"/> <span><b>Little reminder</b><br/>Kamu tidak harus sempurna. Konsisten itu cukup.</span></div></main>}
function App(){return <BrowserRouter><Shell><Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<Login/>}/><Route path="/profile" element={<Profile/>}/><Route path="/glossary" element={<Glossary/>}/><Route path="/section/:sectionId" element={<SectionOverview/>}/><Route path="/section/:sectionId/recap" element={<Recap/>}/><Route path="/section/:sectionId/level/:levelId" element={<LevelHub/>}/><Route path="/section/:sectionId/level/:levelId/materi" element={<Materi/>}/><Route path="/section/:sectionId/level/:levelId/quiz" element={<Quiz/>}/><Route path="/section/:sectionId/level/:levelId/result" element={<Result/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></Shell></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>);
