import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Heart,Lock,ChevronRight,BookOpen,Flame,UserRound,Star,Check,Volume2,Info,Menu} from 'lucide-react';
import './styles.css';
import './translation.css';

const lessons=[
 {id:1,title:'Kokoro & sonchō',sub:'Martabat dan empati',icon:'🌸',color:'pink',locked:false,questions:5},
 {id:2,title:'Jiritsu shien',sub:'Dukung, jangan mengambil alih',icon:'🧸',color:'coral',locked:false,questions:5},
 {id:3,title:'Komunikasi lembut',sub:'Mendengar dengan hati',icon:'💌',color:'lavender',locked:false,questions:5},
 {id:4,title:'Kaigo no kihon',sub:'Dasar-dasar介護',icon:'🍓',color:'mint',locked:false,questions:5},
 {id:5,title:'Seikatsu shien',sub:'Dukungan aktivitas harian',icon:'🫧',color:'yellow',locked:true,questions:5},
 {id:6,title:'Kokoro to karada',sub:'Tubuh dan pikiran',icon:'🩷',color:'pink',locked:true,questions:5},
 {id:7,title:'Ninchishō',sub:'Memahami demensia',icon:'🌷',color:'coral',locked:true,questions:5},
 {id:8,title:'Shōgai no rikai',sub:'Pemahaman disabilitas',icon:'🎀',color:'lavender',locked:true,questions:5},
 {id:9,title:'Iryōteki care',sub:'Perawatan medis',icon:'🩺',color:'mint',locked:true,questions:5},
 {id:10,title:'Kaigo katei',sub:'Proses介護',icon:'🧁',color:'yellow',locked:true,questions:5},
];
const questions=[
 {q:'Fさんが自宅に帰ってきたときの状態に該当するものとして、最も適切なものはどれか。',translation:'Manakah istilah yang paling tepat untuk kondisi F-san ketika pulang ke rumah?',choices:['学習障害','強度行動障害','気分障害','短期入所'],choiceTranslations:['Gangguan belajar','Perilaku menantang berat','Gangguan mood','Short stay'],answer:1,why:'強度行動障害 menggambarkan perilaku agresif atau melukai diri yang intens dan berulang sehingga membutuhkan dukungan khusus.',year:'第36回 問123'},
 {q:'利用者が自分でできる部分がある場合、介護福祉職の対応として最も適切なものはどれか。',translation:'Jika pengguna masih mampu melakukan sebagian aktivitas sendiri, sikap介護福祉職 yang paling tepat adalah apa?',choices:['すべて介助して、早く終わらせる','何も手伝わずに見守る','できる部分は自分で行えるように支援する','家族にすべて任せる'],choiceTranslations:['Membantu semuanya agar cepat selesai','Tidak membantu sama sekali dan hanya melihat','Mendukung agar bagian yang mampu dikerjakan sendiri','Menyerahkan semuanya kepada keluarga'],answer:2,why:'自立支援 berarti mendukung kemampuan dan pilihan pengguna, bukan mengambil alih seluruh aktivitas.',year:'介護の基本'},
 {q:'Gさんへのコミュニケーションとして、最も適切なものはどれか。',translation:'Cara komunikasi yang paling tepat kepada G-san adalah yang mana?',choices:['後ろから声をかける','一対一で向かい合って話す','好きな音楽を大きな音で流す','小さな声で話す'],choiceTranslations:['Berbicara dari belakang','Berbicara berhadapan satu lawan satu','Memutar musik kesukaannya dengan volume keras','Berbicara dengan suara kecil'],answer:1,why:'Posisi berhadapan membantu pengguna memanfaatkan gerak bibir dan ekspresi; kurangi kebisingan.',year:'第37回 問125'},
];
function App(){const [tab,setTab]=useState('learn');const [active,setActive]=useState(null);const [qi,setQi]=useState(0);const [selected,setSelected]=useState(null);const [showTranslation,setShowTranslation]=useState(false);const [showChoiceTranslation,setShowChoiceTranslation]=useState(false);const [streak,setStreak]=useState(3);const [xp,setXp]=useState(120);const [done,setDone]=useState(()=>JSON.parse(localStorage.getItem('kitty-done')||'[]'));
 const start=(lesson)=>{if(lesson.locked)return;setActive(lesson);setQi(0);setSelected(null);setShowTranslation(false);setShowChoiceTranslation(false)};
 const choose=(i)=>{if(selected!==null)return;setSelected(i);setShowChoiceTranslation(false);if(i===questions[qi%questions.length].answer){setXp(x=>x+10);setStreak(x=>x+1)}};
 const next=()=>{if(qi<4){setQi(q=>q+1);setSelected(null);setShowTranslation(false);setShowChoiceTranslation(false)}else{let d=[...done,active.id];setDone(d);localStorage.setItem('kitty-done',JSON.stringify(d));setActive(null);setSelected(null)}};
 const question=questions[qi%questions.length];
 return <div className="app"><header><div className="brand"><div className="kitty">🎀</div><div><b>kaigo kitty</b><small>learn with care</small></div></div><div className="topStats"><span><Flame size={18} fill="#ff718f"/> {streak}</span><span><Heart size={18} fill="#ff718f"/> {xp} XP</span><button onClick={()=>setTab('profile')}><UserRound size={20}/></button></div></header>
 <main>{tab==='learn'&&!active&&<><section className="welcome"><div><p className="eyebrow">OHAYŌ, KENSHI 🌷</p><h1>Belajar merawat<br/><em>dengan hati.</em></h1><p className="muted">Pelan-pelan, satu kartu kecil setiap hari.</p></div><div className="mascot">🐱<span>♡</span></div></section><div className="daily"><div><b>Daily care</b><p>1 lesson lagi untuk menjaga streak-mu!</p><div className="progress"><i style={{width:`${Math.min(100,streak*20)}%`}}/></div></div><span className="badge">{streak}/5</span></div><div className="sectionHead"><div><h2>Learning path</h2><p>Dari hati sampai keterampilan ✨</p></div><button className="round"><Menu size={19}/></button></div><div className="path">{lessons.map((l,idx)=><div className={`lessonWrap pos${idx%3}`} key={l.id}><button className={`lesson ${l.color} ${l.locked?'isLocked':''}`} onClick={()=>start(l)}><span className="lessonIcon">{l.locked?<Lock size={25}/>:l.icon}</span>{!l.locked&&<span className="lessonCheck">{done.includes(l.id)?<Check size={14}/>:''}</span>}</button><div className="lessonText"><b>Section {l.id}</b><strong>{l.title}</strong><small>{l.sub} · {l.questions} soal</small></div></div>)}</div></>}
 {tab==='profile'&&<section className="profile"><div className="profileCard"><div className="avatar">🐱</div><h1>Kenshi's care journey</h1><p className="muted">Belajar dengan lembut, tumbuh dengan konsisten.</p><div className="stats"><div><b>{xp}</b><small>total XP</small></div><div><b>{streak}</b><small>day streak</small></div><div><b>{done.length}</b><small>sections</small></div></div></div><div className="tip"><Star fill="#ffb73b"/> <span><b>Little reminder</b><br/>Kamu tidak harus sempurna. Konsisten itu cukup.</span></div></section>}
 {active&&<section className="quiz"><button className="back" onClick={()=>setActive(null)}>‹ Learning path</button><div className="quizTop"><span>SECTION {active.id}</span><span>{qi+1} / 5</span></div><div className="quizProgress"><i style={{width:`${(qi+1)*20}%`}}/></div><div className="questionCard"><div className="questionIcon">{active.icon}</div><p className="source">{question.year}</p><h1>{question.q}</h1><button className="translateToggle" onClick={()=>setShowTranslation(v=>!v)}>{showTranslation?'Tutup terjemahan':'Klik untuk terjemahan'} <span>{showTranslation?'−':'＋'}</span></button>{showTranslation&&<div className="translation">{question.translation}</div>}<button className="listen"><Volume2 size={17}/> 用語を聞く · Dengarkan istilah</button></div><div className="choices">{question.choices.map((c,i)=><button key={c} onClick={()=>choose(i)} className={selected!==null?(i===question.answer?'correct':i===selected?'wrong':'') :''}><span>{String.fromCharCode(65+i)}</span><div className="choiceCopy"><b>{c}</b>{selected!==null&&showChoiceTranslation&&<small>{question.choiceTranslations[i]}</small>}</div>{selected!==null&&i===question.answer&&<Check/>}</button>)}</div>{selected!==null&&<button className="choiceTranslationToggle" onClick={()=>setShowChoiceTranslation(v=>!v)}>{showChoiceTranslation?'Hide translations':'Show pilihan + terjemahan'} <span>{showChoiceTranslation?'−':'＋'}</span></button>}{selected!==null&&<div className={`explain ${selected===question.answer?'good':''}`}><Info/><div><b>{selected===question.answer?'Sugoi! Jawabanmu tepat.':'Belum tepat, yuk pelajari lagi.'}</b><p>{question.why}</p><a href="https://ryuken25.github.io/kenshi-kanji-n4/" target="_blank" rel="noreferrer">Buka kartu istilah →</a></div></div>}{selected!==null&&<button className="continue" onClick={next}>{qi<4?'Lanjut':'Selesaikan section'} <ChevronRight/></button>}</section>}
 </main><nav><button className={tab==='learn'?'active':''} onClick={()=>{setTab('learn');setActive(null)}}><BookOpen/><span>Learn</span></button><button><Star/><span>Review</span></button><button onClick={()=>setTab('profile')} className={tab==='profile'?'active':''}><UserRound/><span>Profile</span></button></nav></div>}
createRoot(document.getElementById('root')).render(<App/>);
